[build]
    command = "chmod a+x ./netlify.sh && ./netlify.sh"
[build.environment]
  NODE_VERSION = "16"
  NPM_FLAGS = "--version" # prevent Netlify npm install

[[redirects]]
  from = “/*”
  to = “/index.html”
  status = 200
  force = false